# Generated by Django 5.2.1 on 2025-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_measurement_calculated_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of patient surgical/procedural history entries. Each entry is expected to follow the schema: { description: str, side: str (left|right|bilateral), date: str (ISO) }.",
            ),
        ),
    ]
